apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: opencost
  namespace: opencost
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`ui.newsd-a.m3s8.issgovernance.com`)
      kind: Rule
      services:
        - name: opencost
          namespace: opencost
          port: 9090
