apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: opencost-exporter
  namespace: opencost-exporter
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`opencost.crawld.m3s8.issgovernance.com`)
      kind: Rule
      services:
        - name: opencost-exporter
          namespace: opencost-exporter
          port: 9003
