apiVersion: v1
kind: Namespace
metadata:
    name: opencost
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencost
  namespace: opencost
spec:
  selector:
    matchLabels:
      app: opencost
      namespace: opencost
  template:
    metadata:
      labels:
        app: opencost
        namespace: opencost
    spec:
      containers:
        - image: quay.io/kubecost1/kubecost-cost-model:latest
          name: opencost-api
          resources:
            requests:
              cpu: "10m"
              memory: "55M"
            limits:
              cpu: "999m"
              memory: "1G"
          ports: 
            - containerPort: 9003
          env:
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: "http://my-prometheus-server.prometheus.svc"
            - name: CLOUD_PROVIDER_API_KEY
              value: "AIzaSyD29bGxmHAVEOBYtgd8sYM2gM2ekfxQX4U"
            - name: CLUSTER_ID
              value: "cluster-one"
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 1001
        - image: quay.io/kubecost1/opencost-ui:latest
          name: opencost-ui
          resources:
            requests:
              cpu: "10m"
              memory: "55M"
            limits:
              cpu: "999m"
              memory: "1G"
          ports: 
            - containerPort: 9090
          imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: opencost-api
  namespace: opencost
spec:
  selector:
    app: opencost
    namespace: opencost
  ports:
    - name: opencost-api
      protocol: TCP
      port: 9003
      targetPort: 9003
---
kind: Service
apiVersion: v1
metadata:
  name: opencost-ui
  namespace: opencost
spec:
  selector:
    app: opencost
    namespace: opencost
  ports:
    - name: opencost-ui
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: opencost
  namespace: opencost
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`opencostui.crawld.m3s8.issgovernance.com`)
    kind: Rule
    services:
    - name: opencost-ui
      port: 9090
  - match: Host(`opencostapi.crawld.m3s8.issgovernance.com`)
    kind: Rule
    services:
    - name: opencost-api
      port: 9003

