kind: Service
apiVersion: v1
metadata:
  name: opencost-exporter
  namespace: opencost-exporter
spec:
  selector:
    app: opencost
  type: ClusterIP
  ports:
    - name: opencost
      port: 9003
      targetPort: 9003
